name = "vent"
compatibility_date = "2023-12-01"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "vent-d1"
database_id = "6e3ca759-56ca-4b68-b3e9-3c9834858a2c"

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"